ALTER TABLE empresa
ADD COLUMN exportador_habitual BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN calificacion_artesanal BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN codigo_artesano VARCHAR(50),
ADD COLUMN agente_retencion BOOLEAN NOT NULL DEFAULT FALSE;
