ALTER TABLE identidad
    ADD COLUMN IF NOT EXISTS genero VARCHAR(30),
    ADD COLUMN IF NOT EXISTS fecha_nacimiento DATE,
    ADD COLUMN IF NOT EXISTS pais VARCHAR(2),
    ADD COLUMN IF NOT EXISTS provincia VARCHAR(120),
    ADD COLUMN IF NOT EXISTS canton VARCHAR(120),
    ADD COLUMN IF NOT EXISTS ciudad VARCHAR(120),
    ADD COLUMN IF NOT EXISTS parroquia VARCHAR(120),
    ADD COLUMN IF NOT EXISTS idioma VARCHAR(10) NOT NULL DEFAULT 'es',
    ADD COLUMN IF NOT EXISTS moneda VARCHAR(3) NOT NULL DEFAULT 'USD',
    ADD COLUMN IF NOT EXISTS zona_horaria VARCHAR(80) NOT NULL DEFAULT 'America/Guayaquil';
